name: Publish npm and deploy stage
on:
    push:
        branches:
            - develop

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions: {}

jobs:
    release:
        # IMPORTANT: prevent this action from running on forks
        if: github.repository == 'louis-lemon/ts-package-template'
        permissions:
            contents: write
            pull-requests: write
        name: Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
                  registry-url: 'https://registry.npmjs.org'

            - uses: pnpm/action-setup@v2
              with:
                  version: 6.0.2

            - run: pnpm i

            - name: Publish to npm
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npx semantic-release

            - name: Deploy to stage server
              run: echo "TODO deploy to stage"
